// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-fUxNRBBzTs1t-qxQVW0IqUDrCEOl0kI',
    appId: '1:407630639774:web:4a1da25badd8bc3189018f',
    messagingSenderId: '407630639774',
    projectId: 'f151-1f301',
    authDomain: 'f151-1f301.firebaseapp.com',
    storageBucket: 'f151-1f301.appspot.com',
    measurementId: 'G-795YH95YS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUlCzdH__7d3XF8hB4j-3DQLS67gwbtuU',
    appId: '1:407630639774:android:ad55af2985810a7a89018f',
    messagingSenderId: '407630639774',
    projectId: 'f151-1f301',
    storageBucket: 'f151-1f301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkBdACkR2L-ZPROt7GK_vi1VxSxUs8qTA',
    appId: '1:407630639774:ios:aa6013a9cc81456889018f',
    messagingSenderId: '407630639774',
    projectId: 'f151-1f301',
    storageBucket: 'f151-1f301.appspot.com',
    androidClientId: '407630639774-tj8h3e578rihdotp7useotgf4jr1ld4i.apps.googleusercontent.com',
    iosClientId: '407630639774-96852e14c40ld1gm49saqb58phm05ok0.apps.googleusercontent.com',
    iosBundleId: 'com.example.f151',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkBdACkR2L-ZPROt7GK_vi1VxSxUs8qTA',
    appId: '1:407630639774:ios:f100c260c56c254289018f',
    messagingSenderId: '407630639774',
    projectId: 'f151-1f301',
    storageBucket: 'f151-1f301.appspot.com',
    androidClientId: '407630639774-tj8h3e578rihdotp7useotgf4jr1ld4i.apps.googleusercontent.com',
    iosClientId: '407630639774-0pcd34un0g8ej4cofp4r4frhle0hockq.apps.googleusercontent.com',
    iosBundleId: 'com.example.f151.RunnerTests',
  );
}
